### ISSUE TITLE
API directory issue

### ISSUE THREAD

**Issue by Rajan417** [spurtcommerce/spurtcommerce#21]
when i run this command "ts-node --pretty utils/create-entities-index.ts"
then it throw me below error in my cmd

node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module './create-entities-index.ts'
Require stack:
- C:\new_wamp64\www\multivendor-marketplace-master\api\utils\imaginaryUncacheableRequireResolveScript
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)[39m
[90m    at Function.resolve (node:internal/modules/cjs/helpers:109:19)[39m
    at requireResolveNonCached (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:549:16)
    at getProjectSearchDir (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:519:40)
    at phase3 (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:267:27)
    at bootstrap (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:47:30)
    at main (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:33:12)
    at Object.<anonymous> (C:\Users\vatsa\AppData\Roaming\npm\node_modules\[4mts-node[24m\dist\bin.js:579:5)
[90m    at Module._compile (node:internal/modules/cjs/loader:1155:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\new_wamp64\\www\\multivendor-marketplace-master\\api\\utils\\imaginaryUncacheableRequireResolveScript'[39m
  ]
}

**Comment by spurtdeveloper-043** [comment]
Hi @Rajan417 

In Spurtcommerce multivendor-marketplace build, you do NOT have access to the source code of utils/create-entities-index.ts file and hence its impractical for you to execute direct commands like  "ts-node --pretty utils/create-entities-index.ts".

However you can run the whole API build. 
Navigate to api/ folder then execute -> node dist/src/app.js

Please let us know if you need further assistance.
