### ISSUE TITLE
Fails to install npm package for v5.0 api

### ISSUE THREAD

**Issue by mahbub-alam** [spurtcommerce/spurtcommerce#89]
I am getting the following error when I try to install npm package using `npm install` for `src/api`. The development machine is Intel mac with the latest Sequoia version and node v18.20..5. Pre-requisite like `imagemagick` and `graphicsmagick` were also installed using `brew`.

```
npm warn deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated html-pdf@3.0.1: Please migrate your projects to a newer library like puppeteer
npm warn deprecated fstream@1.0.12: This package is no longer supported.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated paypal-rest-sdk@1.8.1: Package no longer supported. The author suggests using the @paypal/paypal-server-sdk package instead: https://www.npmjs.com/package/@paypal/paypal-server-sdk. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
npm warn deprecated puppeteer@19.7.2: < 22.8.2 is no longer supported
npm warn deprecated express-graphql@0.12.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.
npm warn deprecated puppeteer@20.9.0: < 22.8.2 is no longer supported
npm error code 1
npm error path /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick
npm error command failed
npm error command sh -c node-waf clean || (exit 0); node-waf configure build
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@18.20.5 | darwin | arm64
npm error gyp info ok 
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.0.0
npm error gyp info using node@18.20.5 | darwin | arm64
npm error gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
npm error gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
npm error gyp info spawn args [
npm error gyp info spawn args '/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/mark/Library/Caches/node-gyp/18.20.5/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/mark/Library/Caches/node-gyp/18.20.5',
npm error gyp info spawn args '-Dnode_gyp_dir=/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/mark/Library/Caches/node-gyp/18.20.5/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: binding.gyp not found (cwd: /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick) while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error gyp ERR! System Darwin 24.1.0
npm error gyp ERR! command "/Users/mark/.nvm/versions/node/v18.20.5/bin/node" "/Users/mark/.nvm/versions/node/v18.20.5/bin/node-gyp" "configure" "build"
npm error gyp ERR! cwd /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick
npm error gyp ERR! node -v v18.20.5
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /Users/mark/.npm/_logs/2024-12-31T04_10_13_393Z-debug-0.log
```

**Comment by mahbub-alam** [comment]
I tried the same thing on Windows 10 and Linux Mint. Same install problem. I googled it and didn't found any problem. It is unbelievable that nobody faced this problem.

**Comment by spurtcomm** [comment]
> I am getting the following error when I try to install npm package using `npm install` for `src/api`. The development machine is Intel mac with the latest Sequoia version and node v18.20..5. Pre-requisite like `imagemagick` and `graphicsmagick` were also installed using `brew`.
> 
> ```
> npm warn deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> npm warn deprecated @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
> npm warn deprecated npmlog@5.0.1: This package is no longer supported.
> npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated har-validator@5.1.5: this library is no longer supported
> npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
> npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
> npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
> npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
> npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
> npm warn deprecated gauge@3.0.2: This package is no longer supported.
> npm warn deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
> npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm warn deprecated html-pdf@3.0.1: Please migrate your projects to a newer library like puppeteer
> npm warn deprecated fstream@1.0.12: This package is no longer supported.
> npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm warn deprecated paypal-rest-sdk@1.8.1: Package no longer supported. The author suggests using the @paypal/paypal-server-sdk package instead: https://www.npmjs.com/package/@paypal/paypal-server-sdk. Contact Support at https://www.npmjs.com/support for more info.
> npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
> npm warn deprecated puppeteer@19.7.2: < 22.8.2 is no longer supported
> npm warn deprecated express-graphql@0.12.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.
> npm warn deprecated puppeteer@20.9.0: < 22.8.2 is no longer supported
> npm error code 1
> npm error path /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick
> npm error command failed
> npm error command sh -c node-waf clean || (exit 0); node-waf configure build
> npm error gyp info it worked if it ends with ok
> npm error gyp info using node-gyp@11.0.0
> npm error gyp info using node@18.20.5 | darwin | arm64
> npm error gyp info ok 
> npm error gyp info it worked if it ends with ok
> npm error gyp info using node-gyp@11.0.0
> npm error gyp info using node@18.20.5 | darwin | arm64
> npm error gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
> npm error gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
> npm error gyp info spawn args [
> npm error gyp info spawn args '/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/gyp/gyp_main.py',
> npm error gyp info spawn args 'binding.gyp',
> npm error gyp info spawn args '-f',
> npm error gyp info spawn args 'make',
> npm error gyp info spawn args '-I',
> npm error gyp info spawn args '/Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick/build/config.gypi',
> npm error gyp info spawn args '-I',
> npm error gyp info spawn args '/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/addon.gypi',
> npm error gyp info spawn args '-I',
> npm error gyp info spawn args '/Users/mark/Library/Caches/node-gyp/18.20.5/include/node/common.gypi',
> npm error gyp info spawn args '-Dlibrary=shared_library',
> npm error gyp info spawn args '-Dvisibility=default',
> npm error gyp info spawn args '-Dnode_root_dir=/Users/mark/Library/Caches/node-gyp/18.20.5',
> npm error gyp info spawn args '-Dnode_gyp_dir=/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp',
> npm error gyp info spawn args '-Dnode_lib_file=/Users/mark/Library/Caches/node-gyp/18.20.5/<(target_arch)/node.lib',
> npm error gyp info spawn args '-Dmodule_root_dir=/Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick',
> npm error gyp info spawn args '-Dnode_engine=v8',
> npm error gyp info spawn args '--depth=.',
> npm error gyp info spawn args '--no-parallel',
> npm error gyp info spawn args '--generator-output',
> npm error gyp info spawn args 'build',
> npm error gyp info spawn args '-Goutput_dir=.'
> npm error gyp info spawn args ]
> npm error gyp: binding.gyp not found (cwd: /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick) while trying to load binding.gyp
> npm error gyp ERR! configure error 
> npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm error gyp ERR! stack at ChildProcess.<anonymous> (/Users/mark/.nvm/versions/node/v18.20.5/lib/node_modules/node-gyp/lib/configure.js:317:18)
> npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
> npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
> npm error gyp ERR! System Darwin 24.1.0
> npm error gyp ERR! command "/Users/mark/.nvm/versions/node/v18.20.5/bin/node" "/Users/mark/.nvm/versions/node/v18.20.5/bin/node-gyp" "configure" "build"
> npm error gyp ERR! cwd /Users/mark/develop/projects/others/spurtcommerce/api/node_modules/graphicsmagick
> npm error gyp ERR! node -v v18.20.5
> npm error gyp ERR! node-gyp -v v11.0.0
> npm error gyp ERR! not ok
> npm error A complete log of this run can be found in: /Users/mark/.npm/_logs/2024-12-31T04_10_13_393Z-debug-0.log
> ```

First, ensure that your Node.js version is 18.14.2.

**Comment by spurtcomm** [comment]
**Make sure you're using Node.js version 18.14.2**. If not, you can use `nvm` to install and switch to this version. After switching, verify it by running `node -v`. Next, clear the node_modules folder and delete the `package-lock.json` file (if it exists). Finally, reinstall all dependencies by running `npm install`.

**Comment by mahbub-alam** [comment]
I was able to install packages when Node.js version 18.14.2 was installed.
